Repository bcgov/OCWA, pull requests merged in 2019-02, with the labels that each got.

#53 Update and standardize documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  frontend/README.md
  microservices/forumApi/README.md
  microservices/policyApi/README.md
  microservices/requestApi/README.md
  microservices/storageApi/README.md
  microservices/validateApi/README.md
Labels: enhancement

#50 Clean up GitHub issue template formatting
  .github/ISSUE_TEMPLATE/ocwa-template.md
  .github/issue_template.md
Labels: enhancement

#52 Fix rules containing curly brace regex expressions
  microservices/storageApi/demo/public/js/demo.js
  microservices/storageApi/demo/public/lib/tus.min.js
  microservices/validateApi/validator/validator.py
  terraform/scripts/mongodb.tpl
Labels: bug, enhancement

#59 Fix/testdependencies
  .travis.yml
  frontend/package.json
  frontend/server/app.js
  frontend/yarn.lock
  microservices/forumApi/package.json
  microservices/requestApi/package.json
Labels: enhancement

#72 Integration/travis optimization
  .travis.yml
  terraform/ocwa_request_api.tf
  terraform/postgres.tf
  ui_tests/.project
  ui_tests/Include/features/requester/draft_requests.feature
  ui_tests/Include/scripts/groovy/Requester_step_def_ks.groovy
  ui_tests/Object Repository/Page_OCWA Development Version/button_save_close_request.rs
  ui_tests/Object Repository/Page_OCWA Development Version/button_save_request.rs
  ui_tests/Object Repository/Page_OCWA Development Version/div_discussion_form_contenteditable.rs
  ui_tests/Object Repository/Page_OCWA Development Version/span_save_comment.rs
  ui_tests/Scripts/Requester/CreateNewRequestTest/Script1550691552061.groovy
  ui_tests/Scripts/Requester/DraftRequestsTest/Script1550692386417.groovy
  ui_tests/Scripts/Requester/EditPreviouslySubmittedRequestTest/Script1550692490143.groovy
  ui_tests/Scripts/Requester/SeeBlockedFileUploadsTest/Script1550692638707.groovy
  ui_tests/Scripts/Requester/SeeWarningFileUploadsTest/Script1550692586644.groovy
  ui_tests/Scripts/Requester/ViewRequestDetailsTest/Script1550691495862.groovy
  ui_tests/Test Cases/Requester/CreateNewRequestTest.tc
  ui_tests/Test Cases/Requester/DraftRequestsTest.tc
  ui_tests/Test Cases/Requester/EditPreviouslySubmittedRequestTest.tc
  ui_tests/Test Cases/Requester/SeeBlockedFileUploadsTest.tc
  ui_tests/Test Cases/Requester/SeeWarningFileUploadsTest.tc
  ui_tests/Test Cases/Requester/ViewRequestDetailsTest.tc
  ui_tests/Test Suites/CucumberSuite.ts
  ui_tests/settings/internal/com.kms.katalon.composer.testcase.settings.properties
  ui_tests/settings/internal/com.kms.katalon.core.webservice.properties
  ui_tests/settings/internal/com.kms.katalon.execution.properties
  ui_tests/settings/internal/com.kms.katalon.execution.webui.properties
  ui_tests/settings/internal/com.kms.katalon.integration.analytics.properties
Labels: bug
